version: '3.8'
services:
  mosquitto:
    container_name: mosquitto_broker
    build:
      context: ./src/server/mosquitto_broker
      dockerfile: ./dockerfiles/Dockerfile
    hostname: mosquitto_broker
    volumes:
      - ./src/server/mosquitto_broker/conf:/mosquitto/config
      - ./src/server/mosquitto_broker/log:/mosquitto/log
      - ./src/server/mosquitto_broker/data:/mosquitto/data
    restart: always
    ports:
      - "1883:1883"
      - "5353:5353"
    networks:
      - mosquitto_broker
networks:
  mosquitto_broker:
    name: mosquitto_broker
