# SCIoT HTTP Client Configuration

client:
  device_id: "device_01"
  
http:
  server_host: "0.0.0.0"
  server_port: 8000
  endpoints:
    registration: "/api/registration"
    device_input: "/api/device_input"
    offloading_layer: "/api/offloading_layer"
    device_inference_result: "/api/device_inference_result"

model:
  input_height: 96
  input_width: 96
  last_offloading_layer: 58
  image_name: "img.png"
  tflite_subdir: "tflite"
  submodel_prefix: "submodel"
