client:
  client_id: null
  device_id: device_01
delay_simulation:
  computation:
    enabled: true
    mean: 0.002
    std_dev: 0.0005
    type: gaussian
  network:
    enabled: false
http:
  endpoints:
    device_inference_result: /api/device_inference_result
    device_input: /api/device_input
    offloading_layer: /api/offloading_layer
    registration: /api/registration
  server_host: 0.0.0.0
  server_port: 8000
local_inference_mode:
  enabled: true
  probability: 0.1
model:
  image_name: img.png
  input_height: 96
  input_width: 96
  last_offloading_layer: 58
  submodel_prefix: submodel
  tflite_subdir: tflite
